### ISSUE TITLE
 No section: 'Remote Command' exception when opening Preferences from Wizard

### ISSUE THREAD

**Issue by csatt** [csatt/IV_Swinger#211]
Repro:
  1) Run simulator
  2) Click on the simulator run in the Results Wizard
  3) Click on Preferences button
Alternatively, select any run created before the Remote Command feature was added.

Unexpected error: <class 'configparser.NoSectionError'>
Traceback (most recent call last):
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_gui.py", line 1971, in show_preferences
    PreferencesDialog(self)
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_gui.py", line 7588, in __init__
    super().__init__(master=master, title=title,
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_gui.py", line 5426, in __init__
    self.body(body)
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_gui.py", line 7610, in body
    self.populate_rcmd_tab()
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_gui.py", line 9492, in populate_rcmd_tab
    port_number = self.master.config.cfg.getint("Remote Command", "port")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 834, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Remote Command'

**Comment by csatt** [comment]
This fix prevents the NoSectionError but does not allow changes to be made to the Preferences. If a value is changed (on any tab), an error dialog comes up saying "All fields must be integers". This is pretty confusing if the value being changed isn't even numerical. This error message comes from the validate() method of the PreferencesDialog class. It comes from the Remote Command section where the values of self.port_number_str and self.poll_ms_str are checked. But these widgets have nothing filled in, so the check fails.
