### ISSUE TITLE
Simulator doesn't run standalone without existing config file

### ISSUE THREAD

**Issue by csatt** [csatt/IV_Swinger#214]
The simulator (IV_Swinger2_sim.py) is capable of running standalone. However, if this is done before there is an existing config file, it takes an exception and dies.

Traceback (most recent call last):
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_sim.py", line 3363, in <module>
    main()
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_sim.py", line 3358, in main
    SimulatorDialog(main_frame)
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_sim.py", line 1602, in __init__
    self.ivs2_sim = IV_Swinger2_sim(logger=logger,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/GitHub/IV_Swinger/python3/./IV_Swinger2_sim.py", line 459, in __init__
    self.x_pixels = self.config.cfg_snapshot.getint("General", "x pixels")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 834, in getint
    return self._get_conv(section, option, int, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 824, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 819, in _get
    return conv(self.get(section, option, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 797, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/csatt/.pyenv/versions/3.11.2/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/configparser.py", line 1168, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'General'

**Comment by csatt** [comment]
This fix had unintended consequences. Need to fix it in a different way.
